### ISSUE TITLE
Setup Postgres Database

### ISSUE THREAD

**Issue by IndigoShock** [timeCommit-easyAvailability/timeCommit#10]

**Comment by devturner** [comment]
- [ ] models: users_schedule; schedule_settings

- [ ] users_schedule:
- [ ] id, user_id, priority, start_time, end_time, day_of_week, date_created; date_modified, accepted

- [ ] schedule_settings:
- [ ] id, day, start, stop, number_of_shifts, needed_people_per_shift, shifts_occupied

- [ ] company:
- [ ] company_name, company_locations, contact_email
